/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct param {
	int arg1;
	int arg2;
};
typedef struct param param;

#define PROG 0x30001239
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define func0 1
extern  char ** func0_1(void *, CLIENT *);
extern  char ** func0_1_svc(void *, struct svc_req *);
#define func1 2
extern  int * func1_1(char **, CLIENT *);
extern  int * func1_1_svc(char **, struct svc_req *);
#define func2 3
extern  int * func2_1(int *, CLIENT *);
extern  int * func2_1_svc(int *, struct svc_req *);
#define func3 4
extern  int * func3_1(param *, CLIENT *);
extern  int * func3_1_svc(param *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define func0 1
extern  char ** func0_1();
extern  char ** func0_1_svc();
#define func1 2
extern  int * func1_1();
extern  int * func1_1_svc();
#define func2 3
extern  int * func2_1();
extern  int * func2_1_svc();
#define func3 4
extern  int * func3_1();
extern  int * func3_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);

#else /* K&R C */
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
